### ISSUE TITLE
Double slashes on urls

### ISSUE THREAD

**Issue by fritzvd** [HaxePunk/haxepunk.com#8]
Hi,

The games section behaved erratically. Then I saw the urls have a double slash: 
http://haxepunk.com//games/haelstrom.html

Maybe that is the problem. In any case, thought you might want to know

**Comment by h-vishal** [comment]
This issue is because of edit https://github.com/HaxePunk/haxepunk.com/commit/2923ac9ca0f22dc05185b229060e9e3e389f309a 
A leading slash in the url indicates that it is relative to the base url - adding the site.baseurl variable before the url causes the url to be generated with two slashes as indicated in the previous comment. Reverting the change mentioned here will fix the problem and generate the correct url.

**Comment by ibilon** [comment]
Indeed, thanks for finding the bug!
